### PR TITLE
Add cli and update documentation

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks, this is great! everything looks good, the only thing I'm not a fan of is the changes in package.json. actually I like the changes but I'd prefer for that to be a different pr. 

Do you mind changing those back before I merge? thanks!

**Comment by pgilad** [comment]
I'd have to keep some of them to add the required packages... Is that ok?

It's a little bit of a nuance, but no problem :smirk:

**Comment by jonschlinkert** [comment]
I just want the `repository`, `bugs` and `homepage` fields added back.

these templates are used extensively in my documentation:

``` js
<%= bugs.url %>
<%= homepage %>
<%= repository.url %>
```

**Comment by pgilad** [comment]
Oh I see. I rely on NPM's transformation for that in my modules so assumed it's ok.
I hate long package.json s. They are hard to read.

**Comment by pgilad** [comment]
Rebased...

**Comment by jonschlinkert** [comment]
thanks! I appreciate the docs, thanks for rebasing!

**Comment by jonschlinkert** [comment]
bump, published and tagged: https://github.com/jonschlinkert/expand-object/releases/tag/0.1.2.

thanks again

**Pull request merged**
